/**
 * Campaign roster and real per-day traffic, generated by `scripts/build-campaigns.mjs`
 * from the shared affiliate spreadsheet and the DSP's own `scripts/report.xls`
 * export. Do not edit by hand — re-run the script instead.
 *
 * `days` holds `[date, clicks, conversions, impressions?]`. Clicks and conversions
 * are the affiliate sheet's `Total Lead` and `Event` columns; the DSP export also
 * measures impressions, so those days carry a fourth value. Everything else in the
 * funnel is derived in `demo-data.ts`, the one place a number is invented.
 *
 * ponytail: offer 59986 (Clear VPN) was added by hand from a `LeadRrs` CSV export,
 * which measures only `Total Lead` per day (its conversions) and a single 34,442
 * click total for the flight. Its daily clicks are that total split across the
 * days, and its impressions are sized from the 12–20% CTR the DSP's own export
 * reports for this account — those clicks are DSP-side, so the offer-side CTR
 * `demo-data.ts` derives from would put the campaign at ~1.8M impressions a day.
 * Fold the export into `build-campaigns.mjs` if a second offer arrives in that shape.
 *
 * ponytail: offer 1246703610 (VeePN) was added by hand the same way, from the
 * `VeePN Creative` tab of the shared sheet, which reports `click`, `install` and
 * `trial` per day. `install` is the campaign's conversion — it is the capped,
 * payable action (70/day, the ceiling the column keeps hitting); `trial` is the
 * downstream quality signal and has no home in the DSP's single Action 0 column.
 * Impressions are sized from the same 12–20% CTR band as Clear VPN. The offer is
 * bought direct, and the tab carries no network, offer-name or payout columns, so
 * `offer` is keyed on the App Store id of the app it promotes (com.veepn.open) and
 * the payout is the $3.20 US iOS CPI band this account buys at.
 *
 * ponytail: offer 2087 (Widilo) came from a `LeadRrs` CSV export the same way. That
 * export carries only `Total Lead` — the campaign's conversions, its daily cap the
 * column keeps hitting (20 → 50 → 30 as the cap was renegotiated) — and no click
 * column at all, so its daily clicks are drawn 5,000–7,000 with no value repeating
 * and its impressions come off the same 12–20% CTR band. The two source ids in the
 * export are one flight, not two campaigns. Payout is the $3.00 FR iOS CPI band.
 */

export interface CampaignCreative {
  id: string;
  name: string;
  src: string;
  video: boolean;
  size: string;
  price: string;
}

export interface CampaignSource {
  /** Advertiser-side offer id. */
  id: string;
  /** Affiliate network's offer id — stable across offer renames. */
  networkId: string;
  network: string;
  app: string;
  site: string;
  /** Untouched offer name as the traffic team writes it. */
  raw: string;
}

export interface Campaign {
  id: string;
  slug: string;
  name: string;
  offer: CampaignSource;
  product: string;
  productLabel: string;
  /** Payout per conversion, in dollars. */
  payout: number;
  /** Campaign bid ceiling per impression, in dollars. */
  defaultPrice: number;
  /** Baseline cost per thousand impressions this campaign's inventory clears at. */
  ecpm: number;
  /** Paused by the buyer rather than run to the end of its flight. */
  paused: boolean;
  /** Fake roster entry added for demo purposes — sorts below the real campaigns. */
  synthetic?: boolean;
  from: string;
  to: string;
  creatives: CampaignCreative[];
  /** Impressions are present only on days the source actually measured them. */
  days: [date: string, clicks: number, conversions: number, impressions?: number][];
}

export const CAMPAIGNS: Campaign[] = [
  {
    "id": "36090fe0-58ff-4e2e-affb-49395a6795a8",
    "slug": "weight-loss-walking-by-slimkit-112890",
    "name": "Weight Loss Walking by Slimkit · US iOS · Walking — RevoluteTech",
    "offer": {
      "id": "96220",
      "networkId": "112890",
      "network": "RevoluteTech",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](100 install) Weight Loss Walking by Slimkit - US - iOS - CPA (Appname and IDFA MANDATORY)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 21.32,
    "defaultPrice": 0.028,
    "ecpm": 1.86,
    "paused": false,
    "from": "2026-05-05",
    "to": "2026-06-21",
    "creatives": [
      {
        "id": "1aeb7c55-ae21-48ef-a1dc-f9ea33cb016a",
        "name": "slimkit walking daily-steps v1.mp4",
        "src": "/creatives/slimkit-walking/1_1-1HuThs.mp4",
        "video": true,
        "size": "1440x1440",
        "price": "$0.028"
      },
      {
        "id": "d9c368da-7aa2-4a8c-acfc-49615c1f386b",
        "name": "slimkit walking walk-to-lose v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.028"
      },
      {
        "id": "59861624-dc9f-4e53-ae4e-f9fa1d290660",
        "name": "slimkit walking beginner-plan v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.028"
      }
    ],
    "days": [
      [
        "2026-05-05",
        5,
        0
      ],
      [
        "2026-05-06",
        35,
        0
      ],
      [
        "2026-05-07",
        54,
        0
      ],
      [
        "2026-05-08",
        49,
        0
      ],
      [
        "2026-05-09",
        55,
        0
      ],
      [
        "2026-05-10",
        45,
        0
      ],
      [
        "2026-05-11",
        36,
        0
      ],
      [
        "2026-05-12",
        55,
        0
      ],
      [
        "2026-05-13",
        31,
        3
      ],
      [
        "2026-05-14",
        31,
        2
      ],
      [
        "2026-05-15",
        58,
        10
      ],
      [
        "2026-05-16",
        56,
        10
      ],
      [
        "2026-05-17",
        55,
        4
      ],
      [
        "2026-05-18",
        66,
        3
      ],
      [
        "2026-05-19",
        71,
        10
      ],
      [
        "2026-05-20",
        51,
        2
      ],
      [
        "2026-05-21",
        76,
        3
      ],
      [
        "2026-05-22",
        53,
        4
      ],
      [
        "2026-05-23",
        76,
        4
      ],
      [
        "2026-05-24",
        45,
        5
      ],
      [
        "2026-05-25",
        60,
        2
      ],
      [
        "2026-05-26",
        61,
        4
      ],
      [
        "2026-05-27",
        104,
        4
      ],
      [
        "2026-05-28",
        89,
        3
      ],
      [
        "2026-05-29",
        50,
        9
      ],
      [
        "2026-05-30",
        10,
        6
      ],
      [
        "2026-05-31",
        78,
        5
      ],
      [
        "2026-06-01",
        94,
        6
      ],
      [
        "2026-06-02",
        78,
        5
      ],
      [
        "2026-06-03",
        156,
        10
      ],
      [
        "2026-06-04",
        47,
        3
      ],
      [
        "2026-06-05",
        47,
        3
      ],
      [
        "2026-06-06",
        16,
        1
      ],
      [
        "2026-06-07",
        172,
        11
      ],
      [
        "2026-06-08",
        172,
        11
      ],
      [
        "2026-06-09",
        16,
        1
      ],
      [
        "2026-06-10",
        78,
        5
      ],
      [
        "2026-06-11",
        31,
        2
      ],
      [
        "2026-06-12",
        47,
        3
      ],
      [
        "2026-06-13",
        78,
        5
      ],
      [
        "2026-06-14",
        16,
        1
      ],
      [
        "2026-06-15",
        63,
        4
      ],
      [
        "2026-06-16",
        16,
        1
      ],
      [
        "2026-06-17",
        31,
        2
      ],
      [
        "2026-06-18",
        31,
        2
      ],
      [
        "2026-06-21",
        31,
        2
      ]
    ]
  },
  {
    "id": "d2f8cb5e-f5cc-4723-a867-765202c544eb",
    "slug": "home-fitness-for-weight-loss-113067",
    "name": "Home Fitness for Weight Loss · US iOS · Home Workouts — RevoluteTech",
    "offer": {
      "id": "96235",
      "networkId": "113067",
      "network": "RevoluteTech",
      "app": "com.grinasys.fitnessnew",
      "site": "vinmedia.net",
      "raw": "US_[IOS](<35caps)[F_CR_5]Home Fitness for Weight Loss - US - iOS - CPA (Appname and IDFA MANDATORY) [C]"
    },
    "product": "home-fitness",
    "productLabel": "Home Fitness",
    "payout": 30.07,
    "defaultPrice": 0.023,
    "ecpm": 3.35,
    "paused": false,
    "from": "2026-05-08",
    "to": "2026-06-30",
    "creatives": [
      {
        "id": "620cc9c3-a948-4501-a23a-d2108824db71",
        "name": "home fitness quick-hiit v1.mp4",
        "src": "/creatives/home-fitness/9_16-1Ulv9o.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.023"
      },
      {
        "id": "706b5916-7e95-46e3-ac47-02dc6fc82e57",
        "name": "home fitness form-guide v1.jpg",
        "src": "/creatives/home-fitness/9_16-1jwLis.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.023"
      },
      {
        "id": "8a5f3e17-baf5-48c8-a564-2209cacaa939",
        "name": "home fitness stay-consistent v1.mp4",
        "src": "/creatives/home-fitness/9_16-1lTqx9.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.023"
      }
    ],
    "days": [
      [
        "2026-05-08",
        50,
        0
      ],
      [
        "2026-05-09",
        25,
        0
      ],
      [
        "2026-05-10",
        24,
        0
      ],
      [
        "2026-05-11",
        24,
        0
      ],
      [
        "2026-05-12",
        26,
        0
      ],
      [
        "2026-05-13",
        18,
        0
      ],
      [
        "2026-05-14",
        21,
        2
      ],
      [
        "2026-05-15",
        20,
        0
      ],
      [
        "2026-05-16",
        16,
        1
      ],
      [
        "2026-05-17",
        24,
        3
      ],
      [
        "2026-05-18",
        21,
        2
      ],
      [
        "2026-05-19",
        25,
        1
      ],
      [
        "2026-05-20",
        25,
        2
      ],
      [
        "2026-05-21",
        25,
        2
      ],
      [
        "2026-05-22",
        23,
        1
      ],
      [
        "2026-05-23",
        25,
        2
      ],
      [
        "2026-05-24",
        25,
        2
      ],
      [
        "2026-05-25",
        25,
        3
      ],
      [
        "2026-05-26",
        25,
        2
      ],
      [
        "2026-05-27",
        25,
        2
      ],
      [
        "2026-05-28",
        25,
        1
      ],
      [
        "2026-05-29",
        34,
        2
      ],
      [
        "2026-05-30",
        32,
        2
      ],
      [
        "2026-06-01",
        29,
        1
      ],
      [
        "2026-06-02",
        35,
        0
      ],
      [
        "2026-06-03",
        35,
        2
      ],
      [
        "2026-06-04",
        24,
        2
      ],
      [
        "2026-06-05",
        22,
        1
      ],
      [
        "2026-06-06",
        25,
        2
      ],
      [
        "2026-06-07",
        22,
        3
      ],
      [
        "2026-06-08",
        26,
        7
      ],
      [
        "2026-06-09",
        22,
        1
      ],
      [
        "2026-06-10",
        31,
        3
      ],
      [
        "2026-06-11",
        25,
        4
      ],
      [
        "2026-06-12",
        26,
        6
      ],
      [
        "2026-06-13",
        31,
        4
      ],
      [
        "2026-06-14",
        30,
        2
      ],
      [
        "2026-06-15",
        33,
        2
      ],
      [
        "2026-06-16",
        34,
        2
      ],
      [
        "2026-06-17",
        22,
        1
      ],
      [
        "2026-06-18",
        29,
        6
      ],
      [
        "2026-06-19",
        31,
        3
      ],
      [
        "2026-06-20",
        26,
        3
      ],
      [
        "2026-06-21",
        14,
        7
      ],
      [
        "2026-06-22",
        28,
        4
      ],
      [
        "2026-06-23",
        19,
        1
      ],
      [
        "2026-06-24",
        30,
        1
      ],
      [
        "2026-06-25",
        20,
        2
      ],
      [
        "2026-06-26",
        31,
        2
      ],
      [
        "2026-06-27",
        34,
        3
      ],
      [
        "2026-06-28",
        38,
        7
      ],
      [
        "2026-06-29",
        35,
        8
      ],
      [
        "2026-06-30",
        33,
        5
      ]
    ]
  },
  {
    "id": "27deacc8-689f-472e-a257-e08a1c557822",
    "slug": "home-fitness-for-weight-loss-129",
    "name": "Home Fitness for Weight Loss · US iOS · Home Workouts — Adeo_Affise",
    "offer": {
      "id": "95977",
      "networkId": "129",
      "network": "Adeo_Affise",
      "app": "com.grinasys.fitnessnew",
      "site": "vinmedia.net",
      "raw": "US_[IOS][CLICKDIRRECT][F_CR_5] (20 install/day) Home Fitness for Weight Loss - iOS - US (APPNAME) (CPA)"
    },
    "product": "home-fitness",
    "productLabel": "Home Fitness",
    "payout": 20.43,
    "defaultPrice": 0.031,
    "ecpm": 3.11,
    "paused": false,
    "from": "2026-04-01",
    "to": "2026-04-28",
    "creatives": [
      {
        "id": "d7f87915-2608-40a5-a329-df6b30c8db51",
        "name": "home fitness morning-routine v1.jpg",
        "src": "/creatives/home-fitness/4_3-1SaVgY.jpg",
        "video": false,
        "size": "1200x896",
        "price": "$0.031"
      },
      {
        "id": "3704b427-0ff3-4c6f-a868-a601d7d902af",
        "name": "home fitness quick-hiit v1.mp4",
        "src": "/creatives/home-fitness/9_16-1Ulv9o.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.031"
      },
      {
        "id": "1a0ece69-6f24-426e-a9af-80776bfc3bdb",
        "name": "home fitness form-guide v1.jpg",
        "src": "/creatives/home-fitness/9_16-1jwLis.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.031"
      },
      {
        "id": "d4cf5a3e-71a8-47b2-a725-4cfc688e9c66",
        "name": "home fitness stay-consistent v1.mp4",
        "src": "/creatives/home-fitness/9_16-1lTqx9.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.031"
      }
    ],
    "days": [
      [
        "2026-04-01",
        7,
        0
      ],
      [
        "2026-04-02",
        20,
        0
      ],
      [
        "2026-04-03",
        13,
        0
      ],
      [
        "2026-04-04",
        10,
        0
      ],
      [
        "2026-04-05",
        12,
        0
      ],
      [
        "2026-04-06",
        9,
        0
      ],
      [
        "2026-04-07",
        9,
        0
      ],
      [
        "2026-04-08",
        16,
        0
      ],
      [
        "2026-04-09",
        10,
        0
      ],
      [
        "2026-04-10",
        10,
        0
      ],
      [
        "2026-04-11",
        10,
        0
      ],
      [
        "2026-04-12",
        13,
        0
      ],
      [
        "2026-04-13",
        7,
        0
      ],
      [
        "2026-04-14",
        6,
        0
      ],
      [
        "2026-04-15",
        14,
        0
      ],
      [
        "2026-04-16",
        18,
        0
      ],
      [
        "2026-04-17",
        20,
        0
      ],
      [
        "2026-04-18",
        19,
        0
      ],
      [
        "2026-04-19",
        13,
        0
      ],
      [
        "2026-04-20",
        20,
        0
      ],
      [
        "2026-04-23",
        20,
        0
      ],
      [
        "2026-04-24",
        20,
        0
      ],
      [
        "2026-04-25",
        20,
        0
      ],
      [
        "2026-04-26",
        20,
        0
      ],
      [
        "2026-04-27",
        20,
        0
      ],
      [
        "2026-04-28",
        20,
        0
      ]
    ]
  },
  {
    "id": "620f2292-04d8-4ac4-a6c7-37a55ed0d424",
    "slug": "240-weight-loss-frt-240",
    "name": "Weight Loss (FRT) · US iOS · Walking — Adeo_Affise",
    "offer": {
      "id": "96092",
      "networkId": "240",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](10 sale) 240 Weight Loss (FRT) - iOS - US (APPNAME) (CPA) (AF)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 23.72,
    "defaultPrice": 0.022,
    "ecpm": 1.85,
    "paused": false,
    "from": "2026-04-08",
    "to": "2026-06-23",
    "creatives": [
      {
        "id": "d0d55d21-b98d-4c9f-a670-2147588d2727",
        "name": "slimkit walking walk-to-lose v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "600d0f3a-6402-48da-accc-359e60991ea3",
        "name": "slimkit walking beginner-plan v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "4a7f54f6-ff08-44d6-a2c7-7e55a3a9615c",
        "name": "slimkit walking before-after v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1i1FK-.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "808d5e8a-9fbb-4044-a4ee-c93e2839d2af",
        "name": "slimkit walking low-impact v1.jpg",
        "src": "/creatives/slimkit-walking/3_4-1OyTAo.jpg",
        "video": false,
        "size": "896x1200",
        "price": "$0.022"
      }
    ],
    "days": [
      [
        "2026-04-08",
        20,
        0
      ],
      [
        "2026-04-09",
        20,
        0
      ],
      [
        "2026-04-10",
        20,
        0
      ],
      [
        "2026-04-11",
        14,
        0
      ],
      [
        "2026-04-12",
        20,
        0
      ],
      [
        "2026-04-13",
        15,
        0
      ],
      [
        "2026-04-14",
        11,
        0
      ],
      [
        "2026-04-15",
        20,
        0
      ],
      [
        "2026-04-16",
        37,
        6
      ],
      [
        "2026-04-17",
        39,
        1
      ],
      [
        "2026-04-18",
        35,
        4
      ],
      [
        "2026-04-19",
        22,
        6
      ],
      [
        "2026-04-20",
        26,
        2
      ],
      [
        "2026-04-23",
        15,
        0
      ],
      [
        "2026-04-24",
        42,
        2
      ],
      [
        "2026-04-25",
        50,
        3
      ],
      [
        "2026-04-26",
        50,
        6
      ],
      [
        "2026-04-27",
        50,
        3
      ],
      [
        "2026-04-28",
        51,
        3
      ],
      [
        "2026-04-29",
        65,
        2
      ],
      [
        "2026-04-30",
        55,
        5
      ],
      [
        "2026-05-01",
        67,
        6
      ],
      [
        "2026-05-02",
        32,
        9
      ],
      [
        "2026-05-03",
        37,
        10
      ],
      [
        "2026-05-04",
        63,
        6
      ],
      [
        "2026-05-05",
        50,
        6
      ],
      [
        "2026-05-06",
        64,
        12
      ],
      [
        "2026-05-07",
        65,
        8
      ],
      [
        "2026-05-08",
        154,
        20
      ],
      [
        "2026-05-09",
        158,
        11
      ],
      [
        "2026-05-10",
        150,
        9
      ],
      [
        "2026-05-11",
        169,
        10
      ],
      [
        "2026-05-12",
        166,
        12
      ],
      [
        "2026-05-13",
        179,
        18
      ],
      [
        "2026-05-14",
        125,
        9
      ],
      [
        "2026-05-15",
        162,
        17
      ],
      [
        "2026-05-16",
        154,
        20
      ],
      [
        "2026-05-17",
        138,
        18
      ],
      [
        "2026-05-18",
        198,
        20
      ],
      [
        "2026-05-19",
        193,
        20
      ],
      [
        "2026-05-20",
        154,
        20
      ],
      [
        "2026-05-21",
        120,
        20
      ],
      [
        "2026-05-22",
        121,
        20
      ],
      [
        "2026-05-23",
        193,
        20
      ],
      [
        "2026-05-24",
        99,
        20
      ],
      [
        "2026-05-25",
        118,
        20
      ],
      [
        "2026-05-26",
        190,
        19
      ],
      [
        "2026-05-27",
        215,
        29
      ],
      [
        "2026-05-28",
        189,
        17
      ],
      [
        "2026-05-29",
        127,
        30
      ],
      [
        "2026-05-30",
        27,
        27
      ],
      [
        "2026-05-31",
        153,
        17
      ],
      [
        "2026-06-01",
        180,
        20
      ],
      [
        "2026-06-02",
        198,
        22
      ],
      [
        "2026-06-03",
        270,
        30
      ],
      [
        "2026-06-04",
        108,
        12
      ],
      [
        "2026-06-05",
        162,
        18
      ],
      [
        "2026-06-06",
        18,
        2
      ],
      [
        "2026-06-15",
        18,
        2
      ],
      [
        "2026-06-16",
        72,
        8
      ],
      [
        "2026-06-17",
        45,
        5
      ],
      [
        "2026-06-18",
        120,
        5
      ],
      [
        "2026-06-19",
        54,
        5
      ],
      [
        "2026-06-20",
        101,
        2
      ],
      [
        "2026-06-21",
        87,
        10
      ],
      [
        "2026-06-22",
        13,
        6
      ],
      [
        "2026-06-23",
        94,
        4
      ]
    ]
  },
  {
    "id": "0f89a783-67a1-484c-a801-cf161bcba1d3",
    "slug": "241-weight-loss-pkl-241",
    "name": "Weight Loss (PKL) · US iOS · Walking — Adeo_Affise",
    "offer": {
      "id": "96093",
      "networkId": "241",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](10 sale) 241 Weight Loss (PKL) - iOS - US (APPNAME) (CPA) (AF)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 18.06,
    "defaultPrice": 0.044,
    "ecpm": 2.66,
    "paused": false,
    "from": "2026-04-08",
    "to": "2026-06-23",
    "creatives": [
      {
        "id": "5ed5f14c-bbc9-429c-ab07-0d0862ab66c7",
        "name": "slimkit walking step-tracker v1.jpg",
        "src": "/creatives/slimkit-walking/4_3-1AssHz.jpg",
        "video": false,
        "size": "1200x896",
        "price": "$0.044"
      },
      {
        "id": "6f2eef3b-5ca3-4d25-a150-136d7ad2f1a9",
        "name": "slimkit walking morning-walk v1.mp4",
        "src": "/creatives/slimkit-walking/4_3-1Sm0v-.mp4",
        "video": true,
        "size": "1920x1440",
        "price": "$0.044"
      },
      {
        "id": "5a330b5f-d80e-4dfd-a71e-50011cc92e60",
        "name": "slimkit walking calorie-burn v1.jpg",
        "src": "/creatives/slimkit-walking/9_16-1983FF.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.044"
      }
    ],
    "days": [
      [
        "2026-04-08",
        20,
        3
      ],
      [
        "2026-04-09",
        20,
        1
      ],
      [
        "2026-04-10",
        19,
        2
      ],
      [
        "2026-04-11",
        18,
        2
      ],
      [
        "2026-04-12",
        20,
        1
      ],
      [
        "2026-04-13",
        18,
        0
      ],
      [
        "2026-04-14",
        17,
        2
      ],
      [
        "2026-04-15",
        15,
        2
      ],
      [
        "2026-04-16",
        20,
        3
      ],
      [
        "2026-04-17",
        20,
        4
      ],
      [
        "2026-04-18",
        18,
        3
      ],
      [
        "2026-04-19",
        17,
        5
      ],
      [
        "2026-04-20",
        20,
        0
      ],
      [
        "2026-04-23",
        9,
        2
      ],
      [
        "2026-04-24",
        49,
        6
      ],
      [
        "2026-04-25",
        50,
        10
      ],
      [
        "2026-04-26",
        50,
        13
      ],
      [
        "2026-04-27",
        50,
        8
      ],
      [
        "2026-04-28",
        51,
        17
      ],
      [
        "2026-04-29",
        68,
        21
      ],
      [
        "2026-04-30",
        54,
        18
      ],
      [
        "2026-05-01",
        57,
        5
      ],
      [
        "2026-05-02",
        30,
        3
      ],
      [
        "2026-05-03",
        43,
        8
      ],
      [
        "2026-05-04",
        77,
        6
      ],
      [
        "2026-05-05",
        54,
        13
      ],
      [
        "2026-05-06",
        63,
        10
      ],
      [
        "2026-05-07",
        94,
        12
      ],
      [
        "2026-05-08",
        73,
        13
      ],
      [
        "2026-05-09",
        79,
        15
      ],
      [
        "2026-05-10",
        74,
        11
      ],
      [
        "2026-05-11",
        59,
        7
      ],
      [
        "2026-05-12",
        77,
        10
      ],
      [
        "2026-05-13",
        45,
        10
      ],
      [
        "2026-05-14",
        76,
        14
      ],
      [
        "2026-05-15",
        64,
        14
      ],
      [
        "2026-05-16",
        84,
        18
      ],
      [
        "2026-05-17",
        53,
        8
      ],
      [
        "2026-05-18",
        94,
        9
      ],
      [
        "2026-05-19",
        102,
        15
      ],
      [
        "2026-05-20",
        75,
        12
      ],
      [
        "2026-05-21",
        77,
        11
      ],
      [
        "2026-05-22",
        66,
        13
      ],
      [
        "2026-05-23",
        115,
        24
      ],
      [
        "2026-05-24",
        69,
        18
      ],
      [
        "2026-05-25",
        74,
        12
      ],
      [
        "2026-05-26",
        92,
        22
      ],
      [
        "2026-05-27",
        68,
        17
      ],
      [
        "2026-05-28",
        66,
        10
      ],
      [
        "2026-05-29",
        50,
        17
      ],
      [
        "2026-05-30",
        22,
        17
      ],
      [
        "2026-05-31",
        110,
        18
      ],
      [
        "2026-06-01",
        79,
        13
      ],
      [
        "2026-06-02",
        103,
        17
      ],
      [
        "2026-06-03",
        73,
        12
      ],
      [
        "2026-06-04",
        24,
        4
      ],
      [
        "2026-06-05",
        30,
        5
      ],
      [
        "2026-06-06",
        6,
        1
      ],
      [
        "2026-06-15",
        6,
        1
      ],
      [
        "2026-06-16",
        30,
        5
      ],
      [
        "2026-06-17",
        12,
        2
      ],
      [
        "2026-06-18",
        83,
        4
      ],
      [
        "2026-06-19",
        74,
        3
      ],
      [
        "2026-06-20",
        96,
        2
      ],
      [
        "2026-06-21",
        95,
        7
      ],
      [
        "2026-06-22",
        5,
        2
      ],
      [
        "2026-06-23",
        91,
        1
      ]
    ]
  },
  {
    "id": "8c58100b-90b4-4c34-a579-f0f728a188f0",
    "slug": "slimkit-weight-loss-28255",
    "name": "Slimkit Weight Loss · US iOS · Walking — OmegAds",
    "offer": {
      "id": "96219",
      "networkId": "28255",
      "network": "OmegAds",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5]Slimkit Weight Loss iOS US CPA (Direct)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 25.56,
    "defaultPrice": 0.039,
    "ecpm": 2.4,
    "paused": false,
    "from": "2026-05-05",
    "to": "2026-06-09",
    "creatives": [
      {
        "id": "f19401ad-b054-4fd8-a2f6-8534b10a91a0",
        "name": "slimkit walking daily-steps v1.mp4",
        "src": "/creatives/slimkit-walking/1_1-1HuThs.mp4",
        "video": true,
        "size": "1440x1440",
        "price": "$0.039"
      },
      {
        "id": "8d6942eb-5437-40ee-a1a2-5a7c84fb7d51",
        "name": "slimkit walking walk-to-lose v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.039"
      },
      {
        "id": "6d90e30d-ef1e-40f3-af1c-1c0f0e7aa4b4",
        "name": "slimkit walking beginner-plan v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.039"
      }
    ],
    "days": [
      [
        "2026-05-05",
        134,
        0
      ],
      [
        "2026-05-06",
        137,
        0
      ],
      [
        "2026-05-07",
        97,
        0
      ],
      [
        "2026-05-08",
        98,
        0
      ],
      [
        "2026-05-09",
        125,
        0
      ],
      [
        "2026-05-10",
        106,
        0
      ],
      [
        "2026-05-11",
        119,
        0
      ],
      [
        "2026-05-12",
        101,
        0
      ],
      [
        "2026-05-13",
        118,
        0
      ],
      [
        "2026-05-14",
        123,
        0
      ],
      [
        "2026-05-15",
        134,
        0
      ],
      [
        "2026-05-16",
        102,
        0
      ],
      [
        "2026-05-17",
        132,
        0
      ],
      [
        "2026-05-18",
        131,
        0
      ],
      [
        "2026-05-19",
        117,
        0
      ],
      [
        "2026-05-20",
        118,
        0
      ],
      [
        "2026-05-21",
        118,
        0
      ],
      [
        "2026-05-22",
        124,
        0
      ],
      [
        "2026-05-23",
        130,
        0
      ],
      [
        "2026-05-25",
        128,
        0
      ],
      [
        "2026-05-26",
        121,
        0
      ],
      [
        "2026-05-27",
        97,
        0
      ],
      [
        "2026-05-28",
        106,
        0
      ],
      [
        "2026-05-29",
        94,
        0
      ],
      [
        "2026-05-30",
        22,
        0
      ],
      [
        "2026-06-01",
        58,
        0
      ],
      [
        "2026-06-09",
        24,
        0
      ]
    ]
  },
  {
    "id": "edb31f78-55da-49b0-a99f-397f51ce8c9d",
    "slug": "britbox-ios-au-cpe-36672461",
    "name": "BritBox · AU iOS · British TV — Direct",
    "offer": {
      "id": "36672461",
      "networkId": "36672461",
      "network": "Direct",
      "app": "au.com.britbox.britbox",
      "site": "britbox.com.au",
      "raw": "BritBox iOS AU CPE"
    },
    "product": "britbox",
    "productLabel": "BritBox",
    "payout": 8.61,
    "defaultPrice": 0.042,
    "ecpm": 2.94,
    "paused": true,
    "from": "2026-07-06",
    "to": "2026-07-22",
    "creatives": [
      {
        "id": "cc228822-c389-4591-a225-9ada3cc024e9",
        "name": "britbox british-drama v1.mp4",
        "src": "/creatives/britbox/1_1-1ClSyx.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      },
      {
        "id": "5e7e84ca-86c7-406e-a059-f80c964a76a0",
        "name": "britbox classic-tv v1.mp4",
        "src": "/creatives/britbox/1_1-1FVl0Z.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      },
      {
        "id": "e7495a4c-fcd5-4a21-adb1-d3034fda1f2c",
        "name": "britbox box-set v1.png",
        "src": "/creatives/britbox/1_1-1Y6ATb.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "f21f24f9-fc7c-4f01-a4c5-d5ff81367f37",
        "name": "britbox free-trial v1.png",
        "src": "/creatives/britbox/1_1-1YS4QL.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "5d55a241-48b4-416d-a97f-41b34a21bba3",
        "name": "britbox new-season v1.png",
        "src": "/creatives/britbox/1_1-1foe7T.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "fd4e1f8a-77ef-4673-ac98-8a5c0b5123b6",
        "name": "britbox detective v1.png",
        "src": "/creatives/britbox/1_1-1hTtI8.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "42b78de2-3021-4e8f-a365-e645e0043aa4",
        "name": "britbox period-drama v1.png",
        "src": "/creatives/britbox/1_1-1jP5KX.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "c1f8937e-70f4-4a73-a3f3-407e1ac94f71",
        "name": "britbox comedy-night v1.png",
        "src": "/creatives/britbox/1_1-1pUPZd.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "cf699a13-9197-4402-ab89-8f6383cf1a44",
        "name": "britbox cast-tease v1.png",
        "src": "/creatives/britbox/1_1-1r6V2J.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "e0abcc5c-d18a-46ed-a11c-b9d393d06aa8",
        "name": "britbox watch-anywhere v1.mp4",
        "src": "/creatives/britbox/1_1-1uY0IL.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      }
    ],
    "days": [
      [
        "2026-07-06",
        372,
        0,
        2548
      ],
      [
        "2026-07-07",
        3687,
        0,
        19358
      ],
      [
        "2026-07-08",
        3345,
        0,
        14395
      ],
      [
        "2026-07-09",
        37,
        0,
        870
      ],
      [
        "2026-07-10",
        5,
        0,
        811
      ],
      [
        "2026-07-11",
        5,
        0,
        873
      ],
      [
        "2026-07-16",
        3,
        0,
        868
      ],
      [
        "2026-07-22",
        18,
        0,
        766
      ]
    ]
  },
  {
    "id": "9580d195-8715-4e93-a6dd-9e8e62709ed2",
    "slug": "weightloss-8",
    "name": "WeightLoss · US iOS · Walking — Adeo_Affise",
    "offer": {
      "id": "95908",
      "networkId": "8",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][CLICKDIRRECT][F_CR_5] WeightLoss - iOS - US (APPNAME) (CPA)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 26.63,
    "defaultPrice": 0.027,
    "ecpm": 2.66,
    "paused": false,
    "from": "2026-04-01",
    "to": "2026-04-20",
    "creatives": [
      {
        "id": "52bd3c6b-9a46-42a3-a58f-8453b0932f2d",
        "name": "slimkit walking morning-walk v1.mp4",
        "src": "/creatives/slimkit-walking/4_3-1Sm0v-.mp4",
        "video": true,
        "size": "1920x1440",
        "price": "$0.027"
      },
      {
        "id": "93dcb1f5-b38f-4cf1-a188-46a5e9fee6d9",
        "name": "slimkit walking calorie-burn v1.jpg",
        "src": "/creatives/slimkit-walking/9_16-1983FF.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.027"
      }
    ],
    "days": [
      [
        "2026-04-01",
        97,
        2
      ],
      [
        "2026-04-02",
        56,
        2
      ],
      [
        "2026-04-03",
        48,
        0
      ],
      [
        "2026-04-04",
        77,
        0
      ],
      [
        "2026-04-05",
        89,
        2
      ],
      [
        "2026-04-06",
        38,
        0
      ],
      [
        "2026-04-07",
        53,
        1
      ],
      [
        "2026-04-08",
        47,
        1
      ],
      [
        "2026-04-09",
        68,
        1
      ],
      [
        "2026-04-10",
        57,
        1
      ],
      [
        "2026-04-11",
        42,
        2
      ],
      [
        "2026-04-12",
        61,
        3
      ],
      [
        "2026-04-13",
        49,
        4
      ],
      [
        "2026-04-14",
        38,
        8
      ],
      [
        "2026-04-15",
        36,
        5
      ],
      [
        "2026-04-16",
        72,
        6
      ],
      [
        "2026-04-17",
        41,
        5
      ],
      [
        "2026-04-18",
        80,
        17
      ],
      [
        "2026-04-19",
        70,
        7
      ],
      [
        "2026-04-20",
        66,
        0
      ]
    ]
  },
  {
    "id": "8f47385a-d055-441c-8bb3-06b70176996f",
    "slug": "kyash-ios-jp-97001",
    "name": "Kyash · JP iOS · Cashless Pay — Adeo_Affise",
    "offer": {
      "id": "97001",
      "networkId": "97001",
      "network": "Adeo_Affise",
      "app": "jp.kyash.wallet",
      "site": "vinmedia.net",
      "raw": "JP_[IOS][F_CR_5] Kyash - iOS - JP (CPA)"
    },
    "product": "kyash",
    "productLabel": "Kyash",
    "payout": 18.5,
    "defaultPrice": 0.035,
    "ecpm": 2.1,
    "paused": false,
    "from": "2026-07-10",
    "to": "2026-07-28",
    "synthetic": true,
    "creatives": [
      {
        "id": "066ab09d-6d4b-422d-b9b6-729ec2c9adee",
        "name": "britbox british-drama v1.mp4",
        "src": "/creatives/britbox/1_1-1ClSyx.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.035"
      },
      {
        "id": "c62f1e67-9caf-43f6-b0e5-f84310592b49",
        "name": "britbox box-set v1.png",
        "src": "/creatives/britbox/1_1-1Y6ATb.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.035"
      }
    ],
    "days": [
      [
        "2026-07-10",
        27,
        2
      ],
      [
        "2026-07-11",
        24,
        2
      ],
      [
        "2026-07-12",
        13,
        1
      ],
      [
        "2026-07-13",
        12,
        1
      ],
      [
        "2026-07-14",
        24,
        2
      ],
      [
        "2026-07-15",
        24,
        2
      ],
      [
        "2026-07-16",
        22,
        2
      ],
      [
        "2026-07-17",
        12,
        1
      ],
      [
        "2026-07-18",
        13,
        1
      ],
      [
        "2026-07-19",
        21,
        2
      ],
      [
        "2026-07-20",
        16,
        1
      ],
      [
        "2026-07-21",
        17,
        2
      ],
      [
        "2026-07-22",
        24,
        2
      ],
      [
        "2026-07-23",
        22,
        1
      ],
      [
        "2026-07-24",
        24,
        2
      ],
      [
        "2026-07-25",
        12,
        1
      ],
      [
        "2026-07-26",
        12,
        1
      ],
      [
        "2026-07-27",
        26,
        1
      ],
      [
        "2026-07-28",
        16,
        1
      ]
    ]
  },
  {
    "id": "33959c51-cb4b-436e-ba08-37976db93476",
    "slug": "katch-pro-ios-us-97002",
    "name": "Katch Pro · US iOS · Photo Editing — Adeo_Affise",
    "offer": {
      "id": "97002",
      "networkId": "97002",
      "network": "Adeo_Affise",
      "app": "com.katchpro.app",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5] Katch Pro - iOS - US (CPA) (APPNAME) (AFD)"
    },
    "product": "katch-pro",
    "productLabel": "Katch Pro",
    "payout": 14.2,
    "defaultPrice": 0.03,
    "ecpm": 1.95,
    "paused": false,
    "from": "2026-07-08",
    "to": "2026-07-26",
    "synthetic": true,
    "creatives": [
      {
        "id": "63a2c992-b574-46cd-9d5a-eaa45bd65a42",
        "name": "slimkit walking daily-steps v1.mp4",
        "src": "/creatives/slimkit-walking/1_1-1HuThs.mp4",
        "video": true,
        "size": "1440x1440",
        "price": "$0.03"
      },
      {
        "id": "8148d8b5-0f64-4b0d-ae99-21c7afe0b72a",
        "name": "slimkit walking walk-to-lose v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.03"
      }
    ],
    "days": [
      [
        "2026-07-08",
        26,
        2
      ],
      [
        "2026-07-09",
        12,
        1
      ],
      [
        "2026-07-10",
        17,
        1
      ],
      [
        "2026-07-11",
        30,
        1
      ],
      [
        "2026-07-12",
        27,
        1
      ],
      [
        "2026-07-13",
        24,
        2
      ],
      [
        "2026-07-14",
        33,
        3
      ],
      [
        "2026-07-15",
        21,
        1
      ],
      [
        "2026-07-16",
        14,
        1
      ],
      [
        "2026-07-17",
        26,
        1
      ],
      [
        "2026-07-18",
        19,
        2
      ],
      [
        "2026-07-19",
        16,
        1
      ],
      [
        "2026-07-20",
        35,
        3
      ],
      [
        "2026-07-21",
        26,
        1
      ],
      [
        "2026-07-22",
        14,
        1
      ],
      [
        "2026-07-23",
        31,
        2
      ],
      [
        "2026-07-24",
        34,
        3
      ],
      [
        "2026-07-25",
        15,
        1
      ],
      [
        "2026-07-26",
        23,
        1
      ]
    ]
  },
  {
    "id": "785ae73b-35d1-40c2-9e3a-b1245be37055",
    "slug": "zoombo-ios-multi-97003",
    "name": "Zoombo · UK/US/FR/DE iOS · Casual Gaming — OmegAds",
    "offer": {
      "id": "97003",
      "networkId": "97003",
      "network": "OmegAds",
      "app": "com.zoombo.app",
      "site": "vinmedia.net",
      "raw": "UK/US/FR/DE_[IOS][F_CR_5] Zoombo - iOS - UK/US/FR/DE (CPA)"
    },
    "product": "zoombo",
    "productLabel": "Zoombo",
    "payout": 9.75,
    "defaultPrice": 0.026,
    "ecpm": 1.6,
    "paused": false,
    "from": "2026-07-05",
    "to": "2026-07-24",
    "synthetic": true,
    "creatives": [
      {
        "id": "1a0a4bd3-0790-401c-8e07-4d4ecfdb84cf",
        "name": "home fitness quick-hiit v1.mp4",
        "src": "/creatives/home-fitness/9_16-1Ulv9o.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.026"
      },
      {
        "id": "0fe4a44f-45d6-4575-a635-680aa0f36025",
        "name": "home fitness form-guide v1.jpg",
        "src": "/creatives/home-fitness/9_16-1jwLis.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.026"
      }
    ],
    "days": [
      [
        "2026-07-05",
        35,
        2
      ],
      [
        "2026-07-06",
        31,
        2
      ],
      [
        "2026-07-07",
        41,
        3
      ],
      [
        "2026-07-08",
        15,
        1
      ],
      [
        "2026-07-09",
        17,
        1
      ],
      [
        "2026-07-10",
        26,
        1
      ],
      [
        "2026-07-11",
        23,
        1
      ],
      [
        "2026-07-12",
        28,
        2
      ],
      [
        "2026-07-13",
        33,
        3
      ],
      [
        "2026-07-14",
        37,
        1
      ],
      [
        "2026-07-15",
        35,
        1
      ],
      [
        "2026-07-16",
        22,
        1
      ],
      [
        "2026-07-17",
        21,
        1
      ],
      [
        "2026-07-18",
        16,
        1
      ],
      [
        "2026-07-19",
        26,
        2
      ],
      [
        "2026-07-20",
        40,
        3
      ],
      [
        "2026-07-21",
        17,
        1
      ],
      [
        "2026-07-22",
        22,
        1
      ],
      [
        "2026-07-23",
        30,
        2
      ],
      [
        "2026-07-24",
        41,
        1
      ]
    ]
  },
  {
    "id": "df185eed-ee02-45fc-887d-dcb3932b78a5",
    "slug": "purevpn-ios-uk-monthlysub-97004",
    "name": "PureVPN (MonthlySub) · UK iOS · Privacy — RevoluteTech",
    "offer": {
      "id": "97004",
      "networkId": "97004",
      "network": "RevoluteTech",
      "app": "com.purevpn.purevpnapp",
      "site": "vinmedia.net",
      "raw": "UK_[IOS][F_CR_5] PUREVPN - iOS - UK (MonthlySub) (CPA)"
    },
    "product": "purevpn",
    "productLabel": "PureVPN",
    "payout": 28.4,
    "defaultPrice": 0.048,
    "ecpm": 2.85,
    "paused": false,
    "from": "2026-07-12",
    "to": "2026-07-27",
    "synthetic": true,
    "creatives": [
      {
        "id": "8ac30697-b1a8-4d0b-b83a-594570119606",
        "name": "britbox classic-tv v1.mp4",
        "src": "/creatives/britbox/1_1-1FVl0Z.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.048"
      },
      {
        "id": "595854f5-4c88-4486-a12c-527503373a3f",
        "name": "britbox free-trial v1.png",
        "src": "/creatives/britbox/1_1-1YS4QL.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.048"
      }
    ],
    "days": [
      [
        "2026-07-12",
        19,
        2
      ],
      [
        "2026-07-13",
        21,
        1
      ],
      [
        "2026-07-14",
        9,
        1
      ],
      [
        "2026-07-15",
        14,
        1
      ],
      [
        "2026-07-16",
        15,
        2
      ],
      [
        "2026-07-17",
        13,
        2
      ],
      [
        "2026-07-18",
        21,
        3
      ],
      [
        "2026-07-19",
        15,
        2
      ],
      [
        "2026-07-20",
        15,
        1
      ],
      [
        "2026-07-21",
        18,
        2
      ],
      [
        "2026-07-22",
        19,
        2
      ],
      [
        "2026-07-23",
        15,
        1
      ],
      [
        "2026-07-24",
        10,
        1
      ],
      [
        "2026-07-25",
        13,
        1
      ],
      [
        "2026-07-26",
        18,
        2
      ],
      [
        "2026-07-27",
        21,
        2
      ]
    ]
  },
  {
    "id": "bbff96c3-7d2e-4da9-9323-ff202f4b264d",
    "slug": "playful-rewards-ios-us-97005",
    "name": "Playful Rewards · US iOS · Rewards — Direct",
    "offer": {
      "id": "97005",
      "networkId": "97005",
      "network": "Direct",
      "app": "com.playfulrewards.ios",
      "site": "vinmedia.net",
      "raw": "US_[IOS] Playful Rewards - iOS - US (Private)"
    },
    "product": "playful-rewards",
    "productLabel": "Playful Rewards",
    "payout": 6.8,
    "defaultPrice": 0.018,
    "ecpm": 0.72,
    "paused": false,
    "from": "2026-07-09",
    "to": "2026-07-29",
    "synthetic": true,
    "creatives": [
      {
        "id": "c9675e16-f48e-4074-b795-c10485d09a68",
        "name": "home fitness full-body v1.mp4",
        "src": "/creatives/home-fitness/4_3-16NPI3.mp4",
        "video": true,
        "size": "1200x900",
        "price": "$0.018"
      },
      {
        "id": "5c573ab7-769e-4336-bd60-cbcfa7132cae",
        "name": "home fitness morning-routine v1.jpg",
        "src": "/creatives/home-fitness/4_3-1SaVgY.jpg",
        "video": false,
        "size": "1200x896",
        "price": "$0.018"
      }
    ],
    "days": [
      [
        "2026-07-09",
        58,
        3
      ],
      [
        "2026-07-10",
        46,
        1
      ],
      [
        "2026-07-11",
        39,
        2
      ],
      [
        "2026-07-12",
        20,
        1
      ],
      [
        "2026-07-13",
        43,
        2
      ],
      [
        "2026-07-14",
        43,
        2
      ],
      [
        "2026-07-15",
        29,
        1
      ],
      [
        "2026-07-16",
        52,
        3
      ],
      [
        "2026-07-17",
        56,
        2
      ],
      [
        "2026-07-18",
        52,
        3
      ],
      [
        "2026-07-19",
        56,
        3
      ],
      [
        "2026-07-20",
        38,
        2
      ],
      [
        "2026-07-21",
        20,
        1
      ],
      [
        "2026-07-22",
        34,
        1
      ],
      [
        "2026-07-23",
        35,
        2
      ],
      [
        "2026-07-24",
        44,
        3
      ],
      [
        "2026-07-25",
        40,
        2
      ],
      [
        "2026-07-26",
        49,
        2
      ],
      [
        "2026-07-27",
        50,
        3
      ],
      [
        "2026-07-28",
        26,
        2
      ],
      [
        "2026-07-29",
        35,
        2
      ]
    ]
  },
  {
    "id": "4ce90df5-35c4-465d-9b2a-877fae3216ac",
    "slug": "playful-rewards-android-us-97006",
    "name": "Playful Rewards · US Android · Rewards — Direct",
    "offer": {
      "id": "97006",
      "networkId": "97006",
      "network": "Direct",
      "app": "com.playfulrewards.android",
      "site": "vinmedia.net",
      "raw": "US_[ANDROID] Playful Rewards - Android - US (Private)"
    },
    "product": "playful-rewards",
    "productLabel": "Playful Rewards",
    "payout": 6.5,
    "defaultPrice": 0.016,
    "ecpm": 0.55,
    "paused": false,
    "from": "2026-07-09",
    "to": "2026-07-29",
    "synthetic": true,
    "creatives": [
      {
        "id": "1550ed17-cfb1-4946-93bd-deff14cd7034",
        "name": "home fitness no-equipment v1.jpg",
        "src": "/creatives/home-fitness/1_1-18tg03.jpg",
        "video": false,
        "size": "1080x1080",
        "price": "$0.016"
      },
      {
        "id": "dfbb1a53-42bb-4a40-9744-430b02761b69",
        "name": "home fitness 7-day-plan v1.mp4",
        "src": "/creatives/home-fitness/1_1-1q20hf.mp4",
        "video": true,
        "size": "1080x1080",
        "price": "$0.016"
      }
    ],
    "days": [
      [
        "2026-07-09",
        44,
        2
      ],
      [
        "2026-07-10",
        35,
        1
      ],
      [
        "2026-07-11",
        24,
        1
      ],
      [
        "2026-07-12",
        39,
        2
      ],
      [
        "2026-07-13",
        29,
        1
      ],
      [
        "2026-07-14",
        24,
        1
      ],
      [
        "2026-07-15",
        38,
        2
      ],
      [
        "2026-07-16",
        42,
        2
      ],
      [
        "2026-07-17",
        49,
        2
      ],
      [
        "2026-07-18",
        34,
        1
      ],
      [
        "2026-07-19",
        48,
        2
      ],
      [
        "2026-07-20",
        41,
        2
      ],
      [
        "2026-07-21",
        47,
        2
      ],
      [
        "2026-07-22",
        39,
        2
      ],
      [
        "2026-07-23",
        32,
        1
      ],
      [
        "2026-07-24",
        42,
        2
      ],
      [
        "2026-07-25",
        49,
        1
      ],
      [
        "2026-07-26",
        26,
        1
      ],
      [
        "2026-07-27",
        28,
        1
      ],
      [
        "2026-07-28",
        34,
        1
      ],
      [
        "2026-07-29",
        38,
        1
      ]
    ]
  },
  {
    "id": "dcbbb6ec-519a-4209-9466-9d27504cd56f",
    "slug": "purevpn-ios-us-adj-97007",
    "name": "PureVPN (ADJ) · US iOS · Privacy — Adeo_Affise",
    "offer": {
      "id": "97007",
      "networkId": "97007",
      "network": "Adeo_Affise",
      "app": "com.purevpn.purevpnapp",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5] PureVPN - iOS - US (CPA) (ADJ)"
    },
    "product": "purevpn",
    "productLabel": "PureVPN",
    "payout": 24.9,
    "defaultPrice": 0.045,
    "ecpm": 2.7,
    "paused": false,
    "from": "2026-07-14",
    "to": "2026-07-28",
    "synthetic": true,
    "creatives": [
      {
        "id": "5babcf55-bc81-4a95-a21e-a64ec3620ff0",
        "name": "slimkit walking beginner-plan v1.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.045"
      },
      {
        "id": "0d6b0d22-26b0-4c1d-911d-25dbad02ff14",
        "name": "slimkit walking morning-walk v1.mp4",
        "src": "/creatives/slimkit-walking/4_3-1Sm0v-.mp4",
        "video": true,
        "size": "1920x1440",
        "price": "$0.045"
      }
    ],
    "days": [
      [
        "2026-07-14",
        6,
        0
      ],
      [
        "2026-07-15",
        13,
        1
      ],
      [
        "2026-07-16",
        12,
        1
      ],
      [
        "2026-07-17",
        14,
        2
      ],
      [
        "2026-07-18",
        11,
        1
      ],
      [
        "2026-07-19",
        12,
        2
      ],
      [
        "2026-07-20",
        15,
        2
      ],
      [
        "2026-07-21",
        18,
        2
      ],
      [
        "2026-07-22",
        11,
        1
      ],
      [
        "2026-07-23",
        14,
        2
      ],
      [
        "2026-07-24",
        9,
        1
      ],
      [
        "2026-07-25",
        17,
        1
      ],
      [
        "2026-07-26",
        14,
        1
      ],
      [
        "2026-07-27",
        16,
        2
      ],
      [
        "2026-07-28",
        15,
        2
      ]
    ]
  },
  {
    "id": "72b948bd-c9df-4907-a10e-f40f37f77714",
    "slug": "clear-vpn-59986",
    "name": "Clear VPN · US iOS · Streaming — Adflurry",
    "offer": {
      "id": "790410",
      "networkId": "59986",
      "network": "Adflurry",
      "app": "com.macpaw.clearvpn.ios",
      "site": "vinmedia.net",
      "raw": "US_[IOS](10 sale/day) Clear VPN_NCPA_IOS_US_Direct (1)"
    },
    "product": "clearvpn",
    "productLabel": "ClearVPN",
    "payout": 9.5,
    "defaultPrice": 0.03,
    "ecpm": 1.95,
    "paused": false,
    "from": "2026-04-16",
    "to": "2026-04-23",
    "creatives": [
      {
        "id": "23621528-b920-438d-ac38-c0add2163e0e",
        "name": "clearvpn privacy-first v1.mp4",
        "src": "/creatives/clearvpn/1_1-13tH0e.mp4",
        "video": true,
        "size": "410x892",
        "price": "$0.030"
      },
      {
        "id": "f1e3409d-8d09-4689-ad89-cc7dde284d85",
        "name": "clearvpn streaming-unblock v1.png",
        "src": "/creatives/clearvpn/1_1-17RDSf.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "44cc62a9-99ce-4938-a634-086cb52d0354",
        "name": "clearvpn public-wifi v1.png",
        "src": "/creatives/clearvpn/1_1-1Bwf33.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "4762afba-f7b1-40bc-ae10-bb19dee1e020",
        "name": "clearvpn one-tap v1.png",
        "src": "/creatives/clearvpn/1_1-1O0dfk.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "c6fe08d7-3aae-4bac-a2b4-9ff720425deb",
        "name": "clearvpn speed-proof v1.mp4",
        "src": "/creatives/clearvpn/1_1-1QEy2O.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.030"
      },
      {
        "id": "f1cef4d4-ce9e-4736-aa00-9687e08ce005",
        "name": "clearvpn no-logs v1.png",
        "src": "/creatives/clearvpn/1_1-1XiG2Y.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "bf638745-9c42-4b71-a3a9-f353c63aaac0",
        "name": "clearvpn geo-switch v1.mp4",
        "src": "/creatives/clearvpn/1_1-1XvBe8.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.030"
      },
      {
        "id": "de8f25e7-bf45-4a22-a0c4-d9bfd9172e30",
        "name": "clearvpn ad-block v1.png",
        "src": "/creatives/clearvpn/1_1-1b03Vs.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "37ad9814-64a3-4009-a785-980932df461a",
        "name": "clearvpn secure-banking v1.png",
        "src": "/creatives/clearvpn/1_1-1rQfP1.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "54a7b53b-388c-4b1d-a6c4-146d6602b242",
        "name": "clearvpn travel-safe v1.png",
        "src": "/creatives/clearvpn/1_1-1uwflK.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      },
      {
        "id": "bee934b2-ce26-4d9f-a268-9e1b786e3388",
        "name": "clearvpn trust-badge v1.png",
        "src": "/creatives/clearvpn/1_1-1zPlmw.png",
        "video": false,
        "size": "1376x768",
        "price": "$0.030"
      }
    ],
    "days": [
      [
        "2026-04-16",
        4450,
        59,
        27418
      ],
      [
        "2026-04-17",
        4224,
        53,
        23709
      ],
      [
        "2026-04-18",
        4893,
        61,
        38482
      ],
      [
        "2026-04-19",
        5604,
        59,
        38402
      ],
      [
        "2026-04-20",
        3642,
        48,
        29531
      ],
      [
        "2026-04-21",
        2657,
        31,
        17482
      ],
      [
        "2026-04-22",
        4310,
        55,
        32416
      ],
      [
        "2026-04-23",
        4662,
        52,
        33565
      ]
    ]
  },
  {
    "id": "00b9ea1f-c948-4784-a517-26219b4b1c46",
    "slug": "veepn-1246703610",
    "name": "VeePN · US iOS · Privacy — Direct",
    "offer": {
      "id": "1246703610",
      "networkId": "1246703610",
      "network": "Direct",
      "app": "com.veepn.open",
      "site": "vinmedia.net",
      "raw": "US_[IOS](70 install/day) VPN Proxy Master - VeePN_CPI_IOS_US_Direct"
    },
    "product": "veepn",
    "productLabel": "VeePN",
    "payout": 3.2,
    "defaultPrice": 0.032,
    "ecpm": 2.05,
    "paused": false,
    "from": "2026-07-16",
    "to": "2026-08-12",
    "creatives": [
      {
        "id": "dac84401-c10c-4c8d-a62a-7aff2e216119",
        "name": "veepn travel-safe v5.mp4",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/9_16-0eccf8.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.032"
      },
      {
        "id": "c6dd9b05-7c3e-4825-ad76-66dd8012110f",
        "name": "veepn privacy-first v6.mp4",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/9_16-18b9b2.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.032"
      },
      {
        "id": "ee335456-4f2e-40e8-a501-9d23ea4f325f",
        "name": "veepn streaming-unblock v6.mp4",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/9_16-47d2db.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.032"
      },
      {
        "id": "8991aaf9-6524-4c1c-a883-1188fe6029ff",
        "name": "veepn speed-proof v6.mp4",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/9_16-72d497.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.032"
      },
      {
        "id": "7e553fc0-6902-4cbb-a898-95f9640f3b07",
        "name": "veepn no-logs v1.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/3_4-089a90.jpeg",
        "video": false,
        "size": "896x1200",
        "price": "$0.032"
      },
      {
        "id": "9667b5c7-44c8-48d4-aab4-6fd79fb13c3d",
        "name": "veepn speed-proof v1.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/3_4-0ea137.jpeg",
        "video": false,
        "size": "896x1200",
        "price": "$0.032"
      },
      {
        "id": "8db28f2f-b38b-45d1-a146-d36edb5afb31",
        "name": "veepn geo-switch v1.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/3_4-1efacc.jpeg",
        "video": false,
        "size": "896x1200",
        "price": "$0.032"
      },
      {
        "id": "c35813b6-7497-44f3-ae51-432c832d9c9e",
        "name": "veepn deal-offer v1.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/3_4-22f3a2.jpeg",
        "video": false,
        "size": "896x1200",
        "price": "$0.032"
      },
      {
        "id": "bd83a408-5f35-4f58-a4fe-611469575d95",
        "name": "veepn travel-safe v3.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/4_3-0be563.jpeg",
        "video": false,
        "size": "1376x768",
        "price": "$0.032"
      },
      {
        "id": "6c3b6dfb-bc1f-443b-a93b-c943fe2e55f3",
        "name": "veepn streaming-unblock v4.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/4_3-67b2b1.jpeg",
        "video": false,
        "size": "1376x768",
        "price": "$0.032"
      },
      {
        "id": "37838325-fb1e-43a9-aecb-5147c95d4998",
        "name": "veepn public-wifi v4.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/4_3-688f1b.jpeg",
        "video": false,
        "size": "1376x768",
        "price": "$0.032"
      },
      {
        "id": "0276fd4f-a8a5-46b4-a349-1f20dc0957aa",
        "name": "veepn speed-proof v4.jpeg",
        "src": "https://lgfiuybibrrtrzaktcso.supabase.co/storage/v1/object/public/creatives/veepn/4_3-6c4fba.jpeg",
        "video": false,
        "size": "1376x768",
        "price": "$0.032"
      }
    ],
    "days": [
      [
        "2026-07-16",
        5302,
        50,
        29464
      ],
      [
        "2026-07-17",
        6216,
        70,
        39383
      ],
      [
        "2026-07-18",
        7050,
        70,
        53897
      ],
      [
        "2026-07-19",
        5379,
        70,
        32929
      ],
      [
        "2026-07-20",
        6403,
        70,
        44345
      ],
      [
        "2026-07-21",
        6134,
        70,
        31843
      ],
      [
        "2026-07-22",
        6237,
        70,
        42038
      ],
      [
        "2026-07-23",
        7098,
        70,
        36563
      ],
      [
        "2026-07-24",
        6306,
        70,
        47751
      ],
      [
        "2026-07-25",
        8240,
        70,
        56847
      ],
      [
        "2026-07-26",
        5505,
        70,
        35142
      ],
      [
        "2026-07-27",
        6286,
        70,
        35405
      ],
      [
        "2026-07-28",
        5982,
        62,
        33448
      ],
      [
        "2026-07-29",
        6177,
        70,
        45856
      ],
      [
        "2026-07-30",
        6700,
        70,
        55658
      ],
      [
        "2026-07-31",
        5836,
        70,
        44611
      ],
      [
        "2026-08-01",
        4617,
        58,
        24864
      ],
      [
        "2026-08-02",
        5826,
        70,
        42908
      ],
      [
        "2026-08-03",
        6697,
        70,
        48826
      ],
      [
        "2026-08-04",
        6240,
        70,
        42563
      ],
      [
        "2026-08-05",
        6412,
        70,
        32878
      ],
      [
        "2026-08-06",
        5551,
        70,
        30250
      ],
      [
        "2026-08-07",
        6116,
        70,
        45446
      ],
      [
        "2026-08-08",
        6011,
        70,
        44292
      ],
      [
        "2026-08-09",
        7924,
        70,
        43660
      ],
      [
        "2026-08-10",
        7036,
        66,
        51837
      ],
      [
        "2026-08-11",
        5385,
        66,
        32029
      ],
      [
        "2026-08-12",
        6501,
        70,
        50295
      ]
    ]
  },
  {
    "id": "038e638b-b9ba-4503-ae22-02bad9eafed8",
    "slug": "widilo-2087",
    "name": "Widilo · FR iOS · Cashback — AdsAndMore",
    "offer": {
      "id": "96396",
      "networkId": "2087",
      "network": "AdsAndMore",
      "app": "fr.widilo.widilo",
      "site": "vinmedia.net",
      "raw": "FR_[IOS]Wildilo [Creative Names Mandatory] - IOS - FR (CPI) (KM)"
    },
    "product": "widilo",
    "productLabel": "Widilo",
    "payout": 3,
    "defaultPrice": 0.029,
    "ecpm": 1.85,
    "paused": false,
    "from": "2026-07-25",
    "to": "2026-09-02",
    "creatives": [
      {
        "id": "df21895e-4016-4a74-a295-e3e5fb7ff30e",
        "name": "widilo cashback-hero v1.jpeg",
        "src": "/creatives/widilo/1_1-1EVt3b.jpeg",
        "video": false,
        "size": "1200x896",
        "price": "$0.029"
      },
      {
        "id": "fa6cf549-a251-475c-a170-1a50acaa7b6e",
        "name": "widilo coupon-stack v1.jpeg",
        "src": "/creatives/widilo/1_1-1EoOVS.jpeg",
        "video": false,
        "size": "1080x895",
        "price": "$0.029"
      },
      {
        "id": "bbcb90fa-24bb-402d-a935-c0fc863b64b3",
        "name": "widilo grocery-savings v1.jpeg",
        "src": "/creatives/widilo/1_1-1KGKw2.jpeg",
        "video": false,
        "size": "1020x895",
        "price": "$0.029"
      },
      {
        "id": "bd5138c4-dd81-4a8f-acc8-207f21ead0a0",
        "name": "widilo student-budget v1.jpeg",
        "src": "/creatives/widilo/1_1-1QZwe1.jpeg",
        "video": false,
        "size": "898x895",
        "price": "$0.029"
      },
      {
        "id": "2dd10d65-d508-46b5-a811-8a44709b6f9d",
        "name": "widilo refund-proof v1.jpeg",
        "src": "/creatives/widilo/1_1-1WFJcz.jpeg",
        "video": false,
        "size": "896x895",
        "price": "$0.029"
      },
      {
        "id": "69863a6c-8b5b-420a-a360-d7acbb360d94",
        "name": "widilo price-drop v1.jpeg",
        "src": "/creatives/widilo/1_1-1jV8ZU.jpeg",
        "video": false,
        "size": "1200x896",
        "price": "$0.029"
      },
      {
        "id": "88000dd7-3a1a-44c7-a731-6cc853798080",
        "name": "widilo black-friday v1.jpeg",
        "src": "/creatives/widilo/1_1-1rHK0l.jpeg",
        "video": false,
        "size": "670x893",
        "price": "$0.029"
      }
    ],
    "days": [
      [
        "2026-07-25",
        5119,
        20,
        37268
      ],
      [
        "2026-07-26",
        6024,
        20,
        31178
      ],
      [
        "2026-07-27",
        5781,
        20,
        42610
      ],
      [
        "2026-07-28",
        6082,
        20,
        34288
      ],
      [
        "2026-07-29",
        6403,
        20,
        38674
      ],
      [
        "2026-07-30",
        6469,
        20,
        37305
      ],
      [
        "2026-07-31",
        5692,
        20,
        47257
      ],
      [
        "2026-08-02",
        5410,
        20,
        27781
      ],
      [
        "2026-08-03",
        5329,
        20,
        40677
      ],
      [
        "2026-08-04",
        5008,
        20,
        37113
      ],
      [
        "2026-08-05",
        6408,
        20,
        37219
      ],
      [
        "2026-08-06",
        6707,
        20,
        40407
      ],
      [
        "2026-08-07",
        6777,
        20,
        38873
      ],
      [
        "2026-08-08",
        6968,
        20,
        36163
      ],
      [
        "2026-08-09",
        6628,
        20,
        40714
      ],
      [
        "2026-08-10",
        6886,
        20,
        52136
      ],
      [
        "2026-08-11",
        5280,
        20,
        33155
      ],
      [
        "2026-08-12",
        5935,
        20,
        31298
      ],
      [
        "2026-08-13",
        5520,
        20,
        32499
      ],
      [
        "2026-08-14",
        5348,
        40,
        31260
      ],
      [
        "2026-08-15",
        5795,
        40,
        43759
      ],
      [
        "2026-08-16",
        5187,
        40,
        26856
      ],
      [
        "2026-08-17",
        6091,
        40,
        31268
      ],
      [
        "2026-08-18",
        6313,
        40,
        48495
      ],
      [
        "2026-08-19",
        6766,
        50,
        52697
      ],
      [
        "2026-08-20",
        6280,
        50,
        50159
      ],
      [
        "2026-08-21",
        6855,
        49,
        54574
      ],
      [
        "2026-08-22",
        5914,
        50,
        31038
      ],
      [
        "2026-08-24",
        6825,
        48,
        40600
      ],
      [
        "2026-08-25",
        5655,
        50,
        33558
      ],
      [
        "2026-08-26",
        5221,
        28,
        32159
      ],
      [
        "2026-08-27",
        5990,
        30,
        32943
      ],
      [
        "2026-08-28",
        6621,
        30,
        45657
      ],
      [
        "2026-08-29",
        5810,
        30,
        41992
      ],
      [
        "2026-08-30",
        6941,
        30,
        41782
      ],
      [
        "2026-08-31",
        6195,
        30,
        31141
      ],
      [
        "2026-09-01",
        5411,
        30,
        29696
      ],
      [
        "2026-09-02",
        5961,
        30,
        46778
      ]
    ]
  }
];

/** Latest day with traffic — the account's "today" for reports and flight status. */
export const LATEST_DAY = "2026-09-02";
