/**
 * Campaign roster and real per-day traffic, generated by `scripts/build-campaigns.mjs`
 * from the shared affiliate spreadsheet and the DSP's own `scripts/report.xls`
 * export. Do not edit by hand — re-run the script instead.
 *
 * `days` holds `[date, clicks, conversions, impressions?]`. Clicks and conversions
 * are the affiliate sheet's `Total Lead` and `Event` columns; the DSP export also
 * measures impressions, so those days carry a fourth value. Everything else in the
 * funnel is derived in `demo-data.ts`, the one place a number is invented.
 */

export interface CampaignCreative {
  id: string;
  name: string;
  src: string;
  video: boolean;
  size: string;
  price: string;
}

export interface CampaignSource {
  /** Advertiser-side offer id. */
  id: string;
  /** Affiliate network's offer id — stable across offer renames. */
  networkId: string;
  network: string;
  app: string;
  site: string;
  /** Untouched offer name as the traffic team writes it. */
  raw: string;
}

export interface Campaign {
  id: string;
  slug: string;
  name: string;
  offer: CampaignSource;
  product: string;
  productLabel: string;
  /** Payout per conversion, in dollars. */
  payout: number;
  /** Campaign bid ceiling per impression, in dollars. */
  defaultPrice: number;
  /** Baseline cost per thousand impressions this campaign's inventory clears at. */
  ecpm: number;
  /** Paused by the buyer rather than run to the end of its flight. */
  paused: boolean;
  from: string;
  to: string;
  creatives: CampaignCreative[];
  /** Impressions are present only on days the source actually measured them. */
  days: [date: string, clicks: number, conversions: number, impressions?: number][];
}

export const CAMPAIGNS: Campaign[] = [
  {
    "id": "36090fe0-58ff-4e2e-affb-49395a6795a8",
    "slug": "weight-loss-walking-by-slimkit-112890",
    "name": "Weight Loss Walking by Slimkit — RevoluteTech",
    "offer": {
      "id": "96220",
      "networkId": "112890",
      "network": "RevoluteTech",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](100 install) Weight Loss Walking by Slimkit - US - iOS - CPA (Appname and IDFA MANDATORY)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 21.32,
    "defaultPrice": 0.028,
    "ecpm": 1.86,
    "paused": false,
    "from": "2026-05-05",
    "to": "2026-06-21",
    "creatives": [
      {
        "id": "1aeb7c55-ae21-48ef-a1dc-f9ea33cb016a",
        "name": "slimkit walking 1.mp4",
        "src": "/creatives/slimkit-walking/1_1-1HuThs.mp4",
        "video": true,
        "size": "1440x1440",
        "price": "$0.028"
      },
      {
        "id": "d9c368da-7aa2-4a8c-acfc-49615c1f386b",
        "name": "slimkit walking 2.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.028"
      },
      {
        "id": "59861624-dc9f-4e53-ae4e-f9fa1d290660",
        "name": "slimkit walking 3.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.028"
      }
    ],
    "days": [
      [
        "2026-05-05",
        5,
        0
      ],
      [
        "2026-05-06",
        35,
        0
      ],
      [
        "2026-05-07",
        54,
        0
      ],
      [
        "2026-05-08",
        49,
        0
      ],
      [
        "2026-05-09",
        55,
        0
      ],
      [
        "2026-05-10",
        45,
        0
      ],
      [
        "2026-05-11",
        36,
        0
      ],
      [
        "2026-05-12",
        55,
        0
      ],
      [
        "2026-05-13",
        31,
        3
      ],
      [
        "2026-05-14",
        31,
        2
      ],
      [
        "2026-05-15",
        58,
        10
      ],
      [
        "2026-05-16",
        56,
        10
      ],
      [
        "2026-05-17",
        55,
        4
      ],
      [
        "2026-05-18",
        66,
        3
      ],
      [
        "2026-05-19",
        71,
        10
      ],
      [
        "2026-05-20",
        51,
        2
      ],
      [
        "2026-05-21",
        76,
        3
      ],
      [
        "2026-05-22",
        53,
        4
      ],
      [
        "2026-05-23",
        76,
        4
      ],
      [
        "2026-05-24",
        45,
        5
      ],
      [
        "2026-05-25",
        60,
        2
      ],
      [
        "2026-05-26",
        61,
        4
      ],
      [
        "2026-05-27",
        104,
        4
      ],
      [
        "2026-05-28",
        89,
        3
      ],
      [
        "2026-05-29",
        50,
        9
      ],
      [
        "2026-05-30",
        10,
        6
      ],
      [
        "2026-05-31",
        78,
        5
      ],
      [
        "2026-06-01",
        94,
        6
      ],
      [
        "2026-06-02",
        78,
        5
      ],
      [
        "2026-06-03",
        156,
        10
      ],
      [
        "2026-06-04",
        47,
        3
      ],
      [
        "2026-06-05",
        47,
        3
      ],
      [
        "2026-06-06",
        16,
        1
      ],
      [
        "2026-06-07",
        172,
        11
      ],
      [
        "2026-06-08",
        172,
        11
      ],
      [
        "2026-06-09",
        16,
        1
      ],
      [
        "2026-06-10",
        78,
        5
      ],
      [
        "2026-06-11",
        31,
        2
      ],
      [
        "2026-06-12",
        47,
        3
      ],
      [
        "2026-06-13",
        78,
        5
      ],
      [
        "2026-06-14",
        16,
        1
      ],
      [
        "2026-06-15",
        63,
        4
      ],
      [
        "2026-06-16",
        16,
        1
      ],
      [
        "2026-06-17",
        31,
        2
      ],
      [
        "2026-06-18",
        31,
        2
      ],
      [
        "2026-06-21",
        31,
        2
      ]
    ]
  },
  {
    "id": "d2f8cb5e-f5cc-4723-a867-765202c544eb",
    "slug": "home-fitness-for-weight-loss-113067",
    "name": "Home Fitness for Weight Loss — RevoluteTech",
    "offer": {
      "id": "96235",
      "networkId": "113067",
      "network": "RevoluteTech",
      "app": "com.grinasys.fitnessnew",
      "site": "vinmedia.net",
      "raw": "US_[IOS](<35caps)[F_CR_5]Home Fitness for Weight Loss - US - iOS - CPA (Appname and IDFA MANDATORY) [C]"
    },
    "product": "home-fitness",
    "productLabel": "Home Fitness",
    "payout": 30.07,
    "defaultPrice": 0.023,
    "ecpm": 3.35,
    "paused": false,
    "from": "2026-05-08",
    "to": "2026-06-30",
    "creatives": [
      {
        "id": "620cc9c3-a948-4501-a23a-d2108824db71",
        "name": "home fitness 8.mp4",
        "src": "/creatives/home-fitness/9_16-1Ulv9o.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.023"
      },
      {
        "id": "706b5916-7e95-46e3-ac47-02dc6fc82e57",
        "name": "home fitness 9.jpg",
        "src": "/creatives/home-fitness/9_16-1jwLis.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.023"
      },
      {
        "id": "8a5f3e17-baf5-48c8-a564-2209cacaa939",
        "name": "home fitness 10.mp4",
        "src": "/creatives/home-fitness/9_16-1lTqx9.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.023"
      }
    ],
    "days": [
      [
        "2026-05-08",
        50,
        0
      ],
      [
        "2026-05-09",
        25,
        0
      ],
      [
        "2026-05-10",
        24,
        0
      ],
      [
        "2026-05-11",
        24,
        0
      ],
      [
        "2026-05-12",
        26,
        0
      ],
      [
        "2026-05-13",
        18,
        0
      ],
      [
        "2026-05-14",
        21,
        2
      ],
      [
        "2026-05-15",
        20,
        0
      ],
      [
        "2026-05-16",
        16,
        1
      ],
      [
        "2026-05-17",
        24,
        3
      ],
      [
        "2026-05-18",
        21,
        2
      ],
      [
        "2026-05-19",
        25,
        1
      ],
      [
        "2026-05-20",
        25,
        2
      ],
      [
        "2026-05-21",
        25,
        2
      ],
      [
        "2026-05-22",
        23,
        1
      ],
      [
        "2026-05-23",
        25,
        2
      ],
      [
        "2026-05-24",
        25,
        2
      ],
      [
        "2026-05-25",
        25,
        3
      ],
      [
        "2026-05-26",
        25,
        2
      ],
      [
        "2026-05-27",
        25,
        2
      ],
      [
        "2026-05-28",
        25,
        1
      ],
      [
        "2026-05-29",
        34,
        2
      ],
      [
        "2026-05-30",
        32,
        2
      ],
      [
        "2026-06-01",
        29,
        1
      ],
      [
        "2026-06-02",
        35,
        0
      ],
      [
        "2026-06-03",
        35,
        2
      ],
      [
        "2026-06-04",
        24,
        2
      ],
      [
        "2026-06-05",
        22,
        1
      ],
      [
        "2026-06-06",
        25,
        2
      ],
      [
        "2026-06-07",
        22,
        3
      ],
      [
        "2026-06-08",
        26,
        7
      ],
      [
        "2026-06-09",
        22,
        1
      ],
      [
        "2026-06-10",
        31,
        3
      ],
      [
        "2026-06-11",
        25,
        4
      ],
      [
        "2026-06-12",
        26,
        6
      ],
      [
        "2026-06-13",
        31,
        4
      ],
      [
        "2026-06-14",
        30,
        2
      ],
      [
        "2026-06-15",
        33,
        2
      ],
      [
        "2026-06-16",
        34,
        2
      ],
      [
        "2026-06-17",
        22,
        1
      ],
      [
        "2026-06-18",
        29,
        6
      ],
      [
        "2026-06-19",
        31,
        3
      ],
      [
        "2026-06-20",
        26,
        3
      ],
      [
        "2026-06-21",
        14,
        7
      ],
      [
        "2026-06-22",
        28,
        4
      ],
      [
        "2026-06-23",
        19,
        1
      ],
      [
        "2026-06-24",
        30,
        1
      ],
      [
        "2026-06-25",
        20,
        2
      ],
      [
        "2026-06-26",
        31,
        2
      ],
      [
        "2026-06-27",
        34,
        3
      ],
      [
        "2026-06-28",
        38,
        7
      ],
      [
        "2026-06-29",
        35,
        8
      ],
      [
        "2026-06-30",
        33,
        5
      ]
    ]
  },
  {
    "id": "27deacc8-689f-472e-a257-e08a1c557822",
    "slug": "home-fitness-for-weight-loss-129",
    "name": "Home Fitness for Weight Loss — Adeo_Affise",
    "offer": {
      "id": "95977",
      "networkId": "129",
      "network": "Adeo_Affise",
      "app": "com.grinasys.fitnessnew",
      "site": "vinmedia.net",
      "raw": "US_[IOS][CLICKDIRRECT][F_CR_5] (20 install/day) Home Fitness for Weight Loss - iOS - US (APPNAME) (CPA)"
    },
    "product": "home-fitness",
    "productLabel": "Home Fitness",
    "payout": 20.43,
    "defaultPrice": 0.031,
    "ecpm": 3.11,
    "paused": false,
    "from": "2026-04-01",
    "to": "2026-04-28",
    "creatives": [
      {
        "id": "d7f87915-2608-40a5-a329-df6b30c8db51",
        "name": "home fitness 7.jpg",
        "src": "/creatives/home-fitness/4_3-1SaVgY.jpg",
        "video": false,
        "size": "1200x896",
        "price": "$0.031"
      },
      {
        "id": "3704b427-0ff3-4c6f-a868-a601d7d902af",
        "name": "home fitness 8.mp4",
        "src": "/creatives/home-fitness/9_16-1Ulv9o.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.031"
      },
      {
        "id": "1a0ece69-6f24-426e-a9af-80776bfc3bdb",
        "name": "home fitness 9.jpg",
        "src": "/creatives/home-fitness/9_16-1jwLis.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.031"
      },
      {
        "id": "d4cf5a3e-71a8-47b2-a725-4cfc688e9c66",
        "name": "home fitness 10.mp4",
        "src": "/creatives/home-fitness/9_16-1lTqx9.mp4",
        "video": true,
        "size": "1080x1920",
        "price": "$0.031"
      }
    ],
    "days": [
      [
        "2026-04-01",
        7,
        0
      ],
      [
        "2026-04-02",
        20,
        0
      ],
      [
        "2026-04-03",
        13,
        0
      ],
      [
        "2026-04-04",
        10,
        0
      ],
      [
        "2026-04-05",
        12,
        0
      ],
      [
        "2026-04-06",
        9,
        0
      ],
      [
        "2026-04-07",
        9,
        0
      ],
      [
        "2026-04-08",
        16,
        0
      ],
      [
        "2026-04-09",
        10,
        0
      ],
      [
        "2026-04-10",
        10,
        0
      ],
      [
        "2026-04-11",
        10,
        0
      ],
      [
        "2026-04-12",
        13,
        0
      ],
      [
        "2026-04-13",
        7,
        0
      ],
      [
        "2026-04-14",
        6,
        0
      ],
      [
        "2026-04-15",
        14,
        0
      ],
      [
        "2026-04-16",
        18,
        0
      ],
      [
        "2026-04-17",
        20,
        0
      ],
      [
        "2026-04-18",
        19,
        0
      ],
      [
        "2026-04-19",
        13,
        0
      ],
      [
        "2026-04-20",
        20,
        0
      ],
      [
        "2026-04-23",
        20,
        0
      ],
      [
        "2026-04-24",
        20,
        0
      ],
      [
        "2026-04-25",
        20,
        0
      ],
      [
        "2026-04-26",
        20,
        0
      ],
      [
        "2026-04-27",
        20,
        0
      ],
      [
        "2026-04-28",
        20,
        0
      ]
    ]
  },
  {
    "id": "620f2292-04d8-4ac4-a6c7-37a55ed0d424",
    "slug": "240-weight-loss-frt-240",
    "name": "240 Weight Loss (FRT) — Adeo_Affise",
    "offer": {
      "id": "96092",
      "networkId": "240",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](10 sale) 240 Weight Loss (FRT) - iOS - US (APPNAME) (CPA) (AF)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 23.72,
    "defaultPrice": 0.022,
    "ecpm": 1.85,
    "paused": false,
    "from": "2026-04-08",
    "to": "2026-06-23",
    "creatives": [
      {
        "id": "d0d55d21-b98d-4c9f-a670-2147588d2727",
        "name": "slimkit walking 2.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "600d0f3a-6402-48da-accc-359e60991ea3",
        "name": "slimkit walking 3.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "4a7f54f6-ff08-44d6-a2c7-7e55a3a9615c",
        "name": "slimkit walking 4.jpg",
        "src": "/creatives/slimkit-walking/1_1-1i1FK-.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.022"
      },
      {
        "id": "808d5e8a-9fbb-4044-a4ee-c93e2839d2af",
        "name": "slimkit walking 5.jpg",
        "src": "/creatives/slimkit-walking/3_4-1OyTAo.jpg",
        "video": false,
        "size": "896x1200",
        "price": "$0.022"
      }
    ],
    "days": [
      [
        "2026-04-08",
        20,
        0
      ],
      [
        "2026-04-09",
        20,
        0
      ],
      [
        "2026-04-10",
        20,
        0
      ],
      [
        "2026-04-11",
        14,
        0
      ],
      [
        "2026-04-12",
        20,
        0
      ],
      [
        "2026-04-13",
        15,
        0
      ],
      [
        "2026-04-14",
        11,
        0
      ],
      [
        "2026-04-15",
        20,
        0
      ],
      [
        "2026-04-16",
        37,
        6
      ],
      [
        "2026-04-17",
        39,
        1
      ],
      [
        "2026-04-18",
        35,
        4
      ],
      [
        "2026-04-19",
        22,
        6
      ],
      [
        "2026-04-20",
        26,
        2
      ],
      [
        "2026-04-23",
        15,
        0
      ],
      [
        "2026-04-24",
        42,
        2
      ],
      [
        "2026-04-25",
        50,
        3
      ],
      [
        "2026-04-26",
        50,
        6
      ],
      [
        "2026-04-27",
        50,
        3
      ],
      [
        "2026-04-28",
        51,
        3
      ],
      [
        "2026-04-29",
        65,
        2
      ],
      [
        "2026-04-30",
        55,
        5
      ],
      [
        "2026-05-01",
        67,
        6
      ],
      [
        "2026-05-02",
        32,
        9
      ],
      [
        "2026-05-03",
        37,
        10
      ],
      [
        "2026-05-04",
        63,
        6
      ],
      [
        "2026-05-05",
        50,
        6
      ],
      [
        "2026-05-06",
        64,
        12
      ],
      [
        "2026-05-07",
        65,
        8
      ],
      [
        "2026-05-08",
        154,
        20
      ],
      [
        "2026-05-09",
        158,
        11
      ],
      [
        "2026-05-10",
        150,
        9
      ],
      [
        "2026-05-11",
        169,
        10
      ],
      [
        "2026-05-12",
        166,
        12
      ],
      [
        "2026-05-13",
        179,
        18
      ],
      [
        "2026-05-14",
        125,
        9
      ],
      [
        "2026-05-15",
        162,
        17
      ],
      [
        "2026-05-16",
        154,
        20
      ],
      [
        "2026-05-17",
        138,
        18
      ],
      [
        "2026-05-18",
        198,
        20
      ],
      [
        "2026-05-19",
        193,
        20
      ],
      [
        "2026-05-20",
        154,
        20
      ],
      [
        "2026-05-21",
        120,
        20
      ],
      [
        "2026-05-22",
        121,
        20
      ],
      [
        "2026-05-23",
        193,
        20
      ],
      [
        "2026-05-24",
        99,
        20
      ],
      [
        "2026-05-25",
        118,
        20
      ],
      [
        "2026-05-26",
        190,
        19
      ],
      [
        "2026-05-27",
        215,
        29
      ],
      [
        "2026-05-28",
        189,
        17
      ],
      [
        "2026-05-29",
        127,
        30
      ],
      [
        "2026-05-30",
        27,
        27
      ],
      [
        "2026-05-31",
        153,
        17
      ],
      [
        "2026-06-01",
        180,
        20
      ],
      [
        "2026-06-02",
        198,
        22
      ],
      [
        "2026-06-03",
        270,
        30
      ],
      [
        "2026-06-04",
        108,
        12
      ],
      [
        "2026-06-05",
        162,
        18
      ],
      [
        "2026-06-06",
        18,
        2
      ],
      [
        "2026-06-15",
        18,
        2
      ],
      [
        "2026-06-16",
        72,
        8
      ],
      [
        "2026-06-17",
        45,
        5
      ],
      [
        "2026-06-18",
        120,
        5
      ],
      [
        "2026-06-19",
        54,
        5
      ],
      [
        "2026-06-20",
        101,
        2
      ],
      [
        "2026-06-21",
        87,
        10
      ],
      [
        "2026-06-22",
        13,
        6
      ],
      [
        "2026-06-23",
        94,
        4
      ]
    ]
  },
  {
    "id": "0f89a783-67a1-484c-a801-cf161bcba1d3",
    "slug": "241-weight-loss-pkl-241",
    "name": "241 Weight Loss (PKL) — Adeo_Affise",
    "offer": {
      "id": "96093",
      "networkId": "241",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5](10 sale) 241 Weight Loss (PKL) - iOS - US (APPNAME) (CPA) (AF)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 18.06,
    "defaultPrice": 0.044,
    "ecpm": 2.66,
    "paused": false,
    "from": "2026-04-08",
    "to": "2026-06-23",
    "creatives": [
      {
        "id": "5ed5f14c-bbc9-429c-ab07-0d0862ab66c7",
        "name": "slimkit walking 6.jpg",
        "src": "/creatives/slimkit-walking/4_3-1AssHz.jpg",
        "video": false,
        "size": "1200x896",
        "price": "$0.044"
      },
      {
        "id": "6f2eef3b-5ca3-4d25-a150-136d7ad2f1a9",
        "name": "slimkit walking 7.mp4",
        "src": "/creatives/slimkit-walking/4_3-1Sm0v-.mp4",
        "video": true,
        "size": "1920x1440",
        "price": "$0.044"
      },
      {
        "id": "5a330b5f-d80e-4dfd-a71e-50011cc92e60",
        "name": "slimkit walking 8.jpg",
        "src": "/creatives/slimkit-walking/9_16-1983FF.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.044"
      }
    ],
    "days": [
      [
        "2026-04-08",
        20,
        3
      ],
      [
        "2026-04-09",
        20,
        1
      ],
      [
        "2026-04-10",
        19,
        2
      ],
      [
        "2026-04-11",
        18,
        2
      ],
      [
        "2026-04-12",
        20,
        1
      ],
      [
        "2026-04-13",
        18,
        0
      ],
      [
        "2026-04-14",
        17,
        2
      ],
      [
        "2026-04-15",
        15,
        2
      ],
      [
        "2026-04-16",
        20,
        3
      ],
      [
        "2026-04-17",
        20,
        4
      ],
      [
        "2026-04-18",
        18,
        3
      ],
      [
        "2026-04-19",
        17,
        5
      ],
      [
        "2026-04-20",
        20,
        0
      ],
      [
        "2026-04-23",
        9,
        2
      ],
      [
        "2026-04-24",
        49,
        6
      ],
      [
        "2026-04-25",
        50,
        10
      ],
      [
        "2026-04-26",
        50,
        13
      ],
      [
        "2026-04-27",
        50,
        8
      ],
      [
        "2026-04-28",
        51,
        17
      ],
      [
        "2026-04-29",
        68,
        21
      ],
      [
        "2026-04-30",
        54,
        18
      ],
      [
        "2026-05-01",
        57,
        5
      ],
      [
        "2026-05-02",
        30,
        3
      ],
      [
        "2026-05-03",
        43,
        8
      ],
      [
        "2026-05-04",
        77,
        6
      ],
      [
        "2026-05-05",
        54,
        13
      ],
      [
        "2026-05-06",
        63,
        10
      ],
      [
        "2026-05-07",
        94,
        12
      ],
      [
        "2026-05-08",
        73,
        13
      ],
      [
        "2026-05-09",
        79,
        15
      ],
      [
        "2026-05-10",
        74,
        11
      ],
      [
        "2026-05-11",
        59,
        7
      ],
      [
        "2026-05-12",
        77,
        10
      ],
      [
        "2026-05-13",
        45,
        10
      ],
      [
        "2026-05-14",
        76,
        14
      ],
      [
        "2026-05-15",
        64,
        14
      ],
      [
        "2026-05-16",
        84,
        18
      ],
      [
        "2026-05-17",
        53,
        8
      ],
      [
        "2026-05-18",
        94,
        9
      ],
      [
        "2026-05-19",
        102,
        15
      ],
      [
        "2026-05-20",
        75,
        12
      ],
      [
        "2026-05-21",
        77,
        11
      ],
      [
        "2026-05-22",
        66,
        13
      ],
      [
        "2026-05-23",
        115,
        24
      ],
      [
        "2026-05-24",
        69,
        18
      ],
      [
        "2026-05-25",
        74,
        12
      ],
      [
        "2026-05-26",
        92,
        22
      ],
      [
        "2026-05-27",
        68,
        17
      ],
      [
        "2026-05-28",
        66,
        10
      ],
      [
        "2026-05-29",
        50,
        17
      ],
      [
        "2026-05-30",
        22,
        17
      ],
      [
        "2026-05-31",
        110,
        18
      ],
      [
        "2026-06-01",
        79,
        13
      ],
      [
        "2026-06-02",
        103,
        17
      ],
      [
        "2026-06-03",
        73,
        12
      ],
      [
        "2026-06-04",
        24,
        4
      ],
      [
        "2026-06-05",
        30,
        5
      ],
      [
        "2026-06-06",
        6,
        1
      ],
      [
        "2026-06-15",
        6,
        1
      ],
      [
        "2026-06-16",
        30,
        5
      ],
      [
        "2026-06-17",
        12,
        2
      ],
      [
        "2026-06-18",
        83,
        4
      ],
      [
        "2026-06-19",
        74,
        3
      ],
      [
        "2026-06-20",
        96,
        2
      ],
      [
        "2026-06-21",
        95,
        7
      ],
      [
        "2026-06-22",
        5,
        2
      ],
      [
        "2026-06-23",
        91,
        1
      ]
    ]
  },
  {
    "id": "8c58100b-90b4-4c34-a579-f0f728a188f0",
    "slug": "slimkit-weight-loss-28255",
    "name": "Slimkit Weight Loss — OmegAds",
    "offer": {
      "id": "96219",
      "networkId": "28255",
      "network": "OmegAds",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][F_CR_5]Slimkit Weight Loss iOS US CPA (Direct)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 25.56,
    "defaultPrice": 0.039,
    "ecpm": 2.4,
    "paused": false,
    "from": "2026-05-05",
    "to": "2026-06-09",
    "creatives": [
      {
        "id": "f19401ad-b054-4fd8-a2f6-8534b10a91a0",
        "name": "slimkit walking 1.mp4",
        "src": "/creatives/slimkit-walking/1_1-1HuThs.mp4",
        "video": true,
        "size": "1440x1440",
        "price": "$0.039"
      },
      {
        "id": "8d6942eb-5437-40ee-a1a2-5a7c84fb7d51",
        "name": "slimkit walking 2.jpg",
        "src": "/creatives/slimkit-walking/1_1-1XdNRO.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.039"
      },
      {
        "id": "6d90e30d-ef1e-40f3-af1c-1c0f0e7aa4b4",
        "name": "slimkit walking 3.jpg",
        "src": "/creatives/slimkit-walking/1_1-1_t2oR.jpg",
        "video": false,
        "size": "1024x1024",
        "price": "$0.039"
      }
    ],
    "days": [
      [
        "2026-05-05",
        134,
        0
      ],
      [
        "2026-05-06",
        137,
        0
      ],
      [
        "2026-05-07",
        97,
        0
      ],
      [
        "2026-05-08",
        98,
        0
      ],
      [
        "2026-05-09",
        125,
        0
      ],
      [
        "2026-05-10",
        106,
        0
      ],
      [
        "2026-05-11",
        119,
        0
      ],
      [
        "2026-05-12",
        101,
        0
      ],
      [
        "2026-05-13",
        118,
        0
      ],
      [
        "2026-05-14",
        123,
        0
      ],
      [
        "2026-05-15",
        134,
        0
      ],
      [
        "2026-05-16",
        102,
        0
      ],
      [
        "2026-05-17",
        132,
        0
      ],
      [
        "2026-05-18",
        131,
        0
      ],
      [
        "2026-05-19",
        117,
        0
      ],
      [
        "2026-05-20",
        118,
        0
      ],
      [
        "2026-05-21",
        118,
        0
      ],
      [
        "2026-05-22",
        124,
        0
      ],
      [
        "2026-05-23",
        130,
        0
      ],
      [
        "2026-05-25",
        128,
        0
      ],
      [
        "2026-05-26",
        121,
        0
      ],
      [
        "2026-05-27",
        97,
        0
      ],
      [
        "2026-05-28",
        106,
        0
      ],
      [
        "2026-05-29",
        94,
        0
      ],
      [
        "2026-05-30",
        22,
        0
      ],
      [
        "2026-06-01",
        58,
        0
      ],
      [
        "2026-06-09",
        24,
        0
      ]
    ]
  },
  {
    "id": "edb31f78-55da-49b0-a99f-397f51ce8c9d",
    "slug": "britbox-ios-au-cpe-36672461",
    "name": "BritBox iOS AU CPE — Direct",
    "offer": {
      "id": "36672461",
      "networkId": "36672461",
      "network": "Direct",
      "app": "au.com.britbox.britbox",
      "site": "britbox.com.au",
      "raw": "BritBox iOS AU CPE"
    },
    "product": "britbox",
    "productLabel": "BritBox",
    "payout": 8.61,
    "defaultPrice": 0.042,
    "ecpm": 2.94,
    "paused": true,
    "from": "2026-07-06",
    "to": "2026-07-22",
    "creatives": [
      {
        "id": "cc228822-c389-4591-a225-9ada3cc024e9",
        "name": "britbox 1.mp4",
        "src": "/creatives/britbox/1_1-1ClSyx.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      },
      {
        "id": "5e7e84ca-86c7-406e-a059-f80c964a76a0",
        "name": "britbox 2.mp4",
        "src": "/creatives/britbox/1_1-1FVl0Z.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      },
      {
        "id": "e7495a4c-fcd5-4a21-adb1-d3034fda1f2c",
        "name": "britbox 3.png",
        "src": "/creatives/britbox/1_1-1Y6ATb.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "f21f24f9-fc7c-4f01-a4c5-d5ff81367f37",
        "name": "britbox 4.png",
        "src": "/creatives/britbox/1_1-1YS4QL.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "5d55a241-48b4-416d-a97f-41b34a21bba3",
        "name": "britbox 5.png",
        "src": "/creatives/britbox/1_1-1foe7T.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "fd4e1f8a-77ef-4673-ac98-8a5c0b5123b6",
        "name": "britbox 6.png",
        "src": "/creatives/britbox/1_1-1hTtI8.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "42b78de2-3021-4e8f-a365-e645e0043aa4",
        "name": "britbox 7.png",
        "src": "/creatives/britbox/1_1-1jP5KX.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "c1f8937e-70f4-4a73-a3f3-407e1ac94f71",
        "name": "britbox 8.png",
        "src": "/creatives/britbox/1_1-1pUPZd.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "cf699a13-9197-4402-ab89-8f6383cf1a44",
        "name": "britbox 9.png",
        "src": "/creatives/britbox/1_1-1r6V2J.png",
        "video": false,
        "size": "1200x896",
        "price": "$0.042"
      },
      {
        "id": "e0abcc5c-d18a-46ed-a11c-b9d393d06aa8",
        "name": "britbox 10.mp4",
        "src": "/creatives/britbox/1_1-1uY0IL.mp4",
        "video": true,
        "size": "1920x1080",
        "price": "$0.042"
      }
    ],
    "days": [
      [
        "2026-07-06",
        372,
        0,
        2548
      ],
      [
        "2026-07-07",
        3687,
        0,
        19358
      ],
      [
        "2026-07-08",
        3345,
        0,
        14395
      ],
      [
        "2026-07-09",
        37,
        0,
        870
      ],
      [
        "2026-07-10",
        5,
        0,
        811
      ],
      [
        "2026-07-11",
        5,
        0,
        873
      ],
      [
        "2026-07-16",
        3,
        0,
        868
      ],
      [
        "2026-07-22",
        18,
        0,
        766
      ]
    ]
  },
  {
    "id": "9580d195-8715-4e93-a6dd-9e8e62709ed2",
    "slug": "weightloss-8",
    "name": "WeightLoss — Adeo_Affise",
    "offer": {
      "id": "95908",
      "networkId": "8",
      "network": "Adeo_Affise",
      "app": "com.grinasys.walkingfree",
      "site": "vinmedia.net",
      "raw": "US_[IOS][CLICKDIRRECT][F_CR_5] WeightLoss - iOS - US (APPNAME) (CPA)"
    },
    "product": "slimkit-walking",
    "productLabel": "Slimkit Walking",
    "payout": 26.63,
    "defaultPrice": 0.027,
    "ecpm": 2.66,
    "paused": false,
    "from": "2026-04-01",
    "to": "2026-04-20",
    "creatives": [
      {
        "id": "52bd3c6b-9a46-42a3-a58f-8453b0932f2d",
        "name": "slimkit walking 7.mp4",
        "src": "/creatives/slimkit-walking/4_3-1Sm0v-.mp4",
        "video": true,
        "size": "1920x1440",
        "price": "$0.027"
      },
      {
        "id": "93dcb1f5-b38f-4cf1-a188-46a5e9fee6d9",
        "name": "slimkit walking 8.jpg",
        "src": "/creatives/slimkit-walking/9_16-1983FF.jpg",
        "video": false,
        "size": "768x1376",
        "price": "$0.027"
      }
    ],
    "days": [
      [
        "2026-04-01",
        97,
        2
      ],
      [
        "2026-04-02",
        56,
        2
      ],
      [
        "2026-04-03",
        48,
        0
      ],
      [
        "2026-04-04",
        77,
        0
      ],
      [
        "2026-04-05",
        89,
        2
      ],
      [
        "2026-04-06",
        38,
        0
      ],
      [
        "2026-04-07",
        53,
        1
      ],
      [
        "2026-04-08",
        47,
        1
      ],
      [
        "2026-04-09",
        68,
        1
      ],
      [
        "2026-04-10",
        57,
        1
      ],
      [
        "2026-04-11",
        42,
        2
      ],
      [
        "2026-04-12",
        61,
        3
      ],
      [
        "2026-04-13",
        49,
        4
      ],
      [
        "2026-04-14",
        38,
        8
      ],
      [
        "2026-04-15",
        36,
        5
      ],
      [
        "2026-04-16",
        72,
        6
      ],
      [
        "2026-04-17",
        41,
        5
      ],
      [
        "2026-04-18",
        80,
        17
      ],
      [
        "2026-04-19",
        70,
        7
      ],
      [
        "2026-04-20",
        66,
        0
      ]
    ]
  }
];

/** Latest day with traffic — the account's "today" for reports and flight status. */
export const LATEST_DAY = "2026-07-22";
